---
abstract: 'add querySelector and querySelectorAll methods to XML::LibXML nodes'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: XML::LibXML::QuerySelector
name: XML-LibXML-QuerySelector
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  HTML::Selector::XPath: 0.13
  XML::LibXML: 1.70
  perl: 5.8.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=XML-LibXML-QuerySelector
  homepage: https://metacpan.org/release/XML-LibXML-QuerySelector
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/tobyink/p5-xml-libxml-queryselector
version: 0.004
